### ISSUE TITLE
README.md not included

### ISSUE THREAD

**Issue by jdhughes-usgs** [GeospatialPython/pyshp#65] opened 2016-08-19 15:15 UTC
README.md is not included in the pyshp 1.2.8 distribution on PyPI.

**Comment by tacaswell** [comment] 2016-08-20 20:47
This causes `pip install pyshp` to fail https://travis-ci.org/matplotlib/matplotlib/jobs/153746028

**Comment by tacaswell** [comment] 2016-08-20 20:50
This appears to be fixed by 39fbd440c25bea6c2785e0347460aea5b4c51ec4 .

Duplicate of #63

**Comment by karimbahgat** [comment] 2016-09-25 00:48
New version 1.2.10 uploaded to pypi, fixing the pip install issue, also solving matplotlib/matplotlib#6962.

**Closed by karimbahgat** 2016-09-25 00:48 UTC
