### ISSUE TITLE
M values are not optional for shape types with Z geom

### ISSUE THREAD

**Issue by domlysz** [GeospatialPython/pyshp#55] opened 2016-04-23 07:06 UTC
According to SHP spec on wiki (https://en.wikipedia.org/wiki/Shapefile#Shapefile_shape_format_.28.shp.29), M range values are optional but pyshp always expecting them for shape types with Z geom.

`"shapefile.py", line 357, in __shape
    (mmin, mmax) = unpack("<2d", f.read(16))
struct.error: unpack requires a bytes object of length 16`

**Comment by micahcochran** [comment] 2016-04-23 18:27
I looked at the [ESRI 1998 Shapefile Spec](http://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) for guidance about this matter.

It appears that if you have an any Point, Line, Polygon (or other geometry type) with X, Y, and Z coordinates that M (measure) coordinates are included.  But there is a way to make them optional.

From electronic page 6, paper page 2:
> Floating point numbers must be numeric values. Positive infinity, negative infinity, and
Not-a-Number (NaN) values are not allowed in shapefiles. Nevertheless, shapefiles
support the concept of **"no data" values, but they are currently used only for measures**. Any floating point number smaller than –10^38 is considered by a shapefile reader to represent a "no data" value.

It looks like the referenced issue in BlenderGIS has some example data.

**Comment by micahcochran** [comment] 2016-04-23 18:45
I walked through the example shapefile with the Reader.__shapeheader method. 

This isn't verbatim, but I think you get the point.
```Python
In [22]: measure = unpack("<2d", fp.read(16))

In [23]: measure
Out[23]: (-1e+38, -9.999999680285692e+37)
```

Table 1 of the spec (electronic page 8, paper page 4), has a note: `* Unused, with value 0.0, if not Measured or Z type`

There is a line that checks for the self.measure in the header to be 0.0 in Reader.__shape function (https://github.com/GeospatialPython/pyshp/blob/master/shapefile.py#L355).

Either one seems like it is reasonably a valid value.  I'm a little curious what the shapelib's behavior is in GDAL.  I just need to find or convert some data with XYZs.

**Comment by karimbahgat** [comment] 2017-04-17 21:00
That's how I understood the spec as well, that m values are always included. So am I understanding correctly that this means the error was caused by a faulty file where the m values were not included, adn we can close the issue? 

Nevertheless, the issue that you brought up @micahcochran remains. The lib skips reading shape mbox and m values if the total shapefile mbox includes a 0.0. Here is the line you reference along with the original comment:
```
# Read m extremes and values if header m values do not equal 0.0
if shapeType in (13,15,18,23,25,28,31) and not 0.0 in self.measure:
```

Only thing I don't get is why would a 0.0 value indicate that we shouldn't calculate the mbox and m values? Isn't it the "nodata" value we should be looking for, values lower than –10^38? And then we could simply test if the total shapefile mbox has only nodatavalues, since that would mean every mbox and m values must also be nodata and there is no point in reading. If so, this should be an easy fix by instead testing for `...and not (self.measure[0] <= -10e38 and self.measure[1] <= -10e38)`.

**Comment by karimbahgat** [comment] 2018-06-23 16:44
The original issue was about reading the m bounding box for shapes when there was none to be found. After some digging this seems to have been caused by a bug where PyShp used the file header m range to indicate whether it should read m values from shapes. But the code misinterpreted the ESRI spec on the difference between the meaning of 0.0 (can be valid, but also can indicate non-m shapetype) and -10e38 (if all m values in the file were set to nodata). In addition, using the m range values to decide whether to read shape m values is a bit misleading, since a file can be written with faulty m range values, and this should rather be determined directly from the shapetype. 

Changed the code behavior on this in 4f89bebd89802e044e5d92c9e3272f20cfc7d1df.

**Closed by karimbahgat** 2018-06-23 16:44 UTC
Labels: bug, invalid

**Comment by karimbahgat** [comment] 2018-06-23 16:49
See also a8bd8dd4a7ee51431ff1cff268789fbf38b924ff.

**Comment by karimbahgat** [comment] 2019-02-06 21:24
After additional user feedback and re-reading of the specs, seems this problem may also have been caused by m-values that were missing entirely (fields themselves are marked as "optional" in the spec). Have now updated so the code will respect the shaperecord length and only read mranges and mvalues if there is enough data left.
