### ISSUE TITLE
Field name truncated

### ISSUE THREAD

**Issue by pajarrige** [GeospatialPython/pyshp#196] opened 2019-12-17 19:36 UTC
In some circumstances (field names **without** null bytes appended) the field name returned by the reader is truncated by one character; this can result in duplicate field names.
Length of field name should not be decreased by 1 line 898 (pyshp version 2.1.0).

**Comment by karimbahgat** [comment] 2020-12-30 12:48
Do you have a specific example that demonstrates the problem? If I understand you correctly, I believe this is the expected behavior. Decreasing the field name length by 1 is because while the dbf field name can store 11 characters, the 11th character is supposed to be a null-terminator. This is why the shapefile format is known to only allow 10 character field names. Thus, if a shapefile does store an 11 character field name where the 11th character is not a null-terminator, this is only a fluke on the part of the writer; only the first 10 characters can be expected to be retrieved (hence the length minus 1). #2 has more discussion of this topic.

**Comment by karimbahgat** [comment] 2020-12-30 13:14
In looking into this, I did however notice that the pyshp Writer did it the wrong way: instead of capping the field name to the first 10 characters along with an 11th null-terminator, it wrote the first 11 characters of the field name without a null-terminator if the name exceeded the 10 character limit. Although it won't have much practical consequence, I have now fixed this in https://github.com/GeospatialPython/pyshp/commit/4fa635535d72da5f513e9a3b624cea2f3463555d, so thanks for pointing it out.

**Closed** 2021-01-14 13:03 UTC
Labels: enhancement, invalid
